arcamens/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
# from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='site_app:index')),
     url(r'^core_app/', include('core_app.urls', namespace='core_app')), 
     url(r'^group_app/', include('group_app.urls', namespace='group_app')), 
     url(r'^board_app/', include('board_app.urls', namespace='board_app')), 
     url(r'^comment_app/', include('comment_app.urls', namespace='comment_app')), 
     url(r'^site_app/', include('site_app.urls', namespace='site_app')), 
     url(r'^cash_app/', include('cash_app.urls', namespace='cash_app')), 

     url(r'^post_app/', include('post_app.urls', namespace='post_app')), 
     url(r'^group_app/', include('group_app.urls', namespace='group_app')),
     url(r'^paybills/', include('paybills.urls', namespace='paybills')), 
     url(r'^onesignal/', include('onesignal.urls', namespace='onesignal')), 
    url(r'^board_app/', include('board_app.urls', namespace='board_app')),
    url(r'^card_app/', include('card_app.urls', namespace='card_app')),
    url(r'^snippet_app/', include('snippet_app.urls', namespace='snippet_app')),
    url(r'^note_app/', include('note_app.urls', namespace='note_app')),
    url(r'^jscroll/', include('jscroll.urls', namespace='jscroll')),

    url(r'^bitbucket_app/', include('bitbucket_app.urls', namespace='bitbucket_app')),
    url(r'^github_app/', include('github_app.urls', namespace='github_app')),

    url(r'^list_app/', include('list_app.urls', namespace='list_app')),

]


# handler500 = 'core_app.views.default_error'

comment_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list-comments/(?P<event_id>.+)/', views.ListComments.as_view(), name='list-comments'),
    url(r'^e-create-comment/(?P<event_id>.+)/', views.ECreateComment.as_view(), name='e-create-comment'),
    url(r'^create-comment/(?P<event_id>.+)/', views.CreateComment.as_view(), name='create-comment'),
]

group_app/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    # url(r'^group/(?P<group_id>.+)/', views.Group.as_view(), name='group'),
    url(r'^list-posts/(?P<group_id>.+)/', views.ListPosts.as_view(), name='list-posts'),
    url(r'^create-group/(?P<organization_id>.+)', views.CreateGroup.as_view(), name='create-group'),
    url(r'^update-group/(?P<group_id>.+)/', views.UpdateGroup.as_view(), name='update-group'),
    url(r'^delete-group/(?P<group_id>.+)/', views.DeleteGroup.as_view(), name='delete-group'),
    url(r'^manage-user-groups/(?P<user_id>.+)/', views.ManageUserGroups.as_view(), name='manage-user-groups'),
    url(r'^manage-group-users/(?P<group_id>.+)/', views.ManageGroupUsers.as_view(), name='manage-group-users'),
    url(r'^bind-group-user/(?P<group_id>.+)/(?P<user_id>.+)/', views.BindGroupUser.as_view(), name='bind-group-user'),
    url(r'^unbind-group-user/(?P<group_id>.+)/(?P<user_id>.+)/', views.UnbindGroupUser.as_view(), name='unbind-group-user'),
    url(r'^bind-user-group/(?P<group_id>.+)/(?P<user_id>.+)/', views.BindUserGroup.as_view(), name='bind-user-group'),
    url(r'^unbind-user-group/(?P<group_id>.+)/(?P<user_id>.+)/', views.UnbindUserGroup.as_view(), name='unbind-user-group'),

    url(r'^group-link/(?P<group_id>.+)/', views.GroupLink.as_view(), name='group-link'),
    url(r'^pin-group/(?P<group_id>.+)/', views.PinGroup.as_view(), name='pin-group'),
    url(r'^unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    url(r'^select-destin-group/(?P<group_id>.+)/', views.SelectDestinGroup.as_view(), name='select-destin-group'),
    url(r'^paste-post/(?P<group_id>.+)/(?P<post_id>.+)/', views.PastePost.as_view(), name='paste-post'),
    url(r'^paste-all-posts/(?P<group_id>.+)/', views.PasteAllPosts.as_view(), name='paste-all-posts'),

]

post_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^post/(?P<post_id>.+)/', views.Post.as_view(), name='post'),
    url(r'^refresh-post/(?P<post_id>.+)/', views.RefreshPost.as_view(), name='refresh-post'),

    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),
    url(r'^alert-post-workers/(?P<post_id>.+)/', views.AlertPostWorkers.as_view(), name='alert-post-workers'),

    url(r'^done/(?P<post_id>.+)/', views.Done.as_view(), name='done'),
    url(r'^undo/(?P<post_id>.+)/', views.Undo.as_view(), name='undo'),

    url(r'^create-post/(?P<ancestor_id>.+)/', views.CreatePost.as_view(), name='create-post'),
    url(r'^update-post/(?P<post_id>.+)/', views.UpdatePost.as_view(), name='update-post'),
    url(r'^attach-file/(?P<post_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^post-file-download/(?P<filewrapper_id>.+)/', views.PostFileDownload.as_view(), name='post-file-download'),

    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),

    url(r'^post-worker-information/(?P<peer_id>.+)/(?P<post_id>.+)/', views.PostWorkerInformation.as_view(), name='post-worker-information'),
    url(r'^post-tag-information/(?P<tag_id>.+)/(?P<post_id>.+)/', views.PostTagInformation.as_view(), name='post-tag-information'),

    url(r'^manage-post-workers/(?P<post_id>.+)/', views.ManagePostWorkers.as_view(), name='manage-post-workers'),
    url(r'^assign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.AssignPostUser.as_view(), name='assign-post-user'),
    url(r'^unassign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.UnassignPostUser.as_view(), name='unassign-post-user'),
    url(r'^setup-post-filter/(?P<group_id>.+)', views.SetupPostFilter.as_view(), name='setup-post-filter'),
    url(r'^find/', views.Find.as_view(), name='find'),

    url(r'^cut-post/(?P<post_id>.+)/', views.CutPost.as_view(), name='cut-post'),
    url(r'^copy-post/(?P<post_id>.+)/', views.CopyPost.as_view(), name='copy-post'),
    url(r'^manage-post-tags/(?P<post_id>.+)/', views.ManagePostTags.as_view(), name='manage-post-tags'),
    url(r'^bind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.BindPostTag.as_view(), name='bind-post-tag'),
    url(r'^unbind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.UnbindPostTag.as_view(), name='unbind-post-tag'),
    url(r'^request-post-attention/(?P<peer_id>.+)/(?P<post_id>.+)', views.RequestPostAttention.as_view(), name='request-post-attention'),
    url(r'^confirm-post-deletion/(?P<post_id>.+)/', views.ConfirmPostDeletion.as_view(), name='confirm-post-deletion'),
    url(r'^select-fork-list/(?P<post_id>.+)/', views.SelectForkList.as_view(), name='select-fork-list'),
    url(r'^create-post-fork/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.CreatePostFork.as_view(), name='create-post-fork'),
    url(r'^pull-card-content/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.PullCardContent.as_view(), name='pull-card-content'),
    url(r'^post-events/(?P<post_id>.+)/', views.PostEvents.as_view(), name='post-events'),
    url(r'^pin-post/(?P<post_id>.+)/', views.PinPost.as_view(), name='pin-post'),
    url(r'^unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    url(r'^set-post-priority-down/(?P<post0_id>.+)/(?P<post1_id>.+)/', views.SetPostPriorityDown.as_view(), name='set-post-priority-down'),
    url(r'^set-post-priority-up/(?P<post0_id>.+)/(?P<post1_id>.+)/', views.SetPostPriorityUp.as_view(), name='set-post-priority-up'),
    url(r'^post-priority/(?P<post_id>.+)/', views.PostPriority.as_view(), name='post-priority'),

]

group_app/views.py
from group_app.models import Group, ECreateGroup, EDeleteGroup, Groupship,\
EUnbindGroupUser, EUpdateGroup, EPastePost, EBindGroupUser, GroupPin
from post_app.models import Post, PostFilter, GlobalPostFilter
from core_app.models import Organization, User, Clipboard
from core_app.views import GuardianView
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from django.conf import settings
from jscroll.wrappers import JScroll
from django.db.models import Q, F
import post_app.models
import operator
from . import forms
from . import models
import json
# Create your views here.

class ListPosts(GuardianView):
    """
    This view is performed to be executed just if the logged user
    in fact belongs to the group. 

    It also checks if the logged user organization contains the group.
    """

    def get(self, request, group_id):
        # Make sure i belong to the group and my default
        # organization contains the group.
        group = self.me.groups.get(
            id=group_id, organization=self.me.default)

        filter, _ = PostFilter.objects.get_or_create(
        user=self.me, group=group)

        posts     = group.posts.all()
        total     = posts.count()
        boardpins = self.me.boardpin_set.filter(organization=self.me.default)
        listpins  = self.me.listpin_set.filter(organization=self.me.default)
        cardpins  = self.me.cardpin_set.filter(organization=self.me.default)
        postpins = self.me.postpin_set.filter(organization=self.me.default)

        grouppins = self.me.grouppin_set.filter(
        organization=self.me.default)

        posts = filter.collect(posts)
        posts = posts.order_by('-priority')
        count = posts.count()
        elems = JScroll(self.me.id, 'group_app/list-posts-scroll.html', posts)

        env = {'group':group, 'count': count, 'total': total, 
        'grouppins': grouppins, 'elems':elems.as_window(), 'postpins': postpins,
        'filter': filter, 'boardpins': boardpins, 'listpins': listpins, 
        'cardpins': cardpins}

        return render(request, 'group_app/list-posts.html', env)

class CreateGroup(GuardianView):
    """
    As every user has its own workspace everyone can create groups.
    """

    def get(self, request, organization_id):
        form = forms.GroupForm()
        return render(request, 'group_app/create-group.html', 
        {'form':form, 'user_id': self.user_id, 'organization_id':organization_id})

    def post(self, request, organization_id):
        form = forms.GroupForm(request.POST)

        if not form.is_valid():
            return render(request, 'group_app/create-group.html',
                        {'form': form, 'user_id':self.user_id, 
                                'organization_id': organization_id}, status=400)

        organization = Organization.objects.get(id=organization_id)
        record       = form.save()
        record.owner = self.me
        record.organization  = organization
        form.save()

        users = self.me.default.users.all() if record.open else (self.me, )

        groupships = (Groupship(user=ind, group=record, 
        binder=self.me) for ind in users)

        Groupship.objects.bulk_create(groupships)
        event = ECreateGroup.objects.create(organization=self.me.default,
        group=record, user=self.me)

        event.dispatch(*users)

        return redirect('core_app:list-nodes')

class DeleteGroup(GuardianView):
    """
    Just the owner of the group is supposed to delete the group.
    The group also has to be in the logged user default organization.
    """

    def get(self, request,  group_id):
        # Make sure i belong to the organization.
        group = self.me.groups.get(id = group_id,
        organization=self.me.default)

        form = forms.ConfirmGroupDeletionForm()

        return render(request, 'group_app/delete-group.html', 
        {'group': group, 'form': form})

    def post(self, request, group_id):
        group = self.me.groups.get(id = group_id,
        organization=self.me.default)

        if group.owner != self.me:
            return HttpResponse('Just owner can do that!', status=403)

        form = forms.ConfirmGroupDeletionForm(request.POST, 
        confirm_token=group.name)

        if not form.is_valid():
            return render(request, 
                'group_app/delete-group.html', 
                    {'group': group, 'form': form}, status=400)

        event    = EDeleteGroup.objects.create(organization=self.me.default,
        group_name=group.name, user=self.me)

        event.dispatch(*group.users.all())
        group.delete()

        return redirect('core_app:list-nodes')

class BindGroupUser(GuardianView):
    """
    Everyone in the group can perform this view but its default organization
    has to contain the group and the user has to be in the organization of the
    group as well.
    """

    def redirect(self, request, group_id, user_id):
        return ManageGroupUsers.as_view()(request, group_id)

    def post(self, request, group_id, user_id):
        user     = User.objects.get(id=user_id, organizations=self.me.default)
        group = self.me.groups.get(id=group_id, organization=self.me.default)

        Groupship.objects.create(user=user, binder=self.me, group=group)

        event = EBindGroupUser.objects.create(organization=self.me.default,
        group=group, user=self.me, peer=user)
        event.dispatch(*group.users.all())
        return self.redirect(request, group_id, user_id)

class BindUserGroup(BindGroupUser):
    def redirect(self, request, group_id, user_id):
        return ManageUserGroups.as_view()(request, user_id)

class UnbindGroupUser(BindGroupUser):
    """
    Just users whose default organization matches the group organization
    can perform this view. Everyone in group is supposed to add/remove members.
    """

    def post(self, request, group_id, user_id):
        user = User.objects.get(id=user_id, organizations=self.me.default)

        # Make sure i belong to the group.
        group = self.me.groups.get(id=group_id, organization=self.me.default)
        if group.owner == user:
            return HttpResponse("You can't remove the group owner!", status=403)

        event = EUnbindGroupUser.objects.create(organization=self.me.default,
        group=group, user=self.me, peer=user)
        event.dispatch(*group.users.all())
        user.user_groupship.get(group=group).delete()

        return self.redirect(request, group_id, user_id)

class UnbindUserGroup(UnbindGroupUser):
    def redirect(self, request, group_id, user_id):
        return ManageUserGroups.as_view()(request, user_id)

class UpdateGroup(GuardianView):
    """
    Just the owner is supposed to perform this view.
    But for viewing the dialog it is necessary to belong to the group.
    """

    def get(self, request, group_id):
        group = self.me.groups.get(id=group_id, 
        organization=self.me.default)

        return render(request, 'group_app/update-group.html',
        {'group': group, 'form': forms.UpdateGroupForm(instance=group)})

    def post(self, request, group_id):
        record = self.me.groups.get(id=group_id, 
        organization=self.me.default)

        if record.owner != self.me:
            return HttpResponse('Just owner can do that!', status=403)

        form = forms.UpdateGroupForm(request.POST, instance=record)
        if not form.is_valid():
            return render(request, 
                'group_app/update-group.html',
                     {'group': record, 'form': form})
        form.save()

        event = EUpdateGroup.objects.create(
        organization=self.me.default, group=record, user=self.me)
        event.dispatch(*record.users.all())

        return redirect('group_app:list-posts', 
        group_id=record.id)

class SelectDestinGroup(GuardianView):
    def get(self, request, group_id):
        group = models.Group.objects.get(id=group_id, 
        organization=self.me.default, users=self.me)

        clipboard, _ = Clipboard.objects.get_or_create(
        user=self.me, organization=self.me.default)

        posts = clipboard.posts.all()
        total = posts.count() 

        return render(request, 'group_app/select-destin-group.html', 
        {'user': self.me, 'group': group, 'posts': posts,  'total': total})

class PastePost(GuardianView):
    def get(self, request, group_id, post_id):
        group = models.Group.objects.get(id=group_id, 
        organization=self.me.default, users=self.me)

        clipboard, _ = Clipboard.objects.get_or_create(
        user=self.me, organization=self.me.default)

        # Make sure the post is on the user clipboard.
        post = clipboard.posts.get(id=post_id)
        head = group.posts.order_by('-priority').first()

        priority      = head.priority if head else 0
        post.ancestor = group
        post.done     = False

        # Maybe not necessary just +1.
        post.priority = post.priority + priority
        post.save()

        event = EPastePost(organization=self.me.default, 
        group=group, user=self.me)

        event.save(hcache=False)
        event.posts.add(post)
    
        # Workers of the post dont need to be notified of this event
        # because them may not belong to the board at all.
        event.dispatch(*group.users.all())
        event.save()

        clipboard.posts.remove(post)
        return redirect('group_app:select-destin-group', group_id=group.id)

class PasteAllPosts(GuardianView):
    """
    Everyone who belongs to the group is allowed to perform
    this view.
    """

    def get(self, request, group_id):
        # Make sure i belong to the group and my default organization
        # contains it.
        group = self.me.groups.get(
        id=group_id, organization=self.me.default)

        clipboard, _ = Clipboard.objects.get_or_create(
        user=self.me, organization=self.me.default)

group_app/templates/group_app/create-group.html
{% load bootstrap3 %}
{% load i18n %}

<form id="form-group-data" enctype="multipart/form-data">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>

{% block title %}
<h4 class="modal-title"> <span class="glyphicon glyphicon-eye-open"></span> Group</h4>
{% endblock %}

</div>
<div class="modal-body">
{% csrf_token %}
{% bootstrap_field form.name  size='sm' %}
{% bootstrap_field form.description  size='sm' %}
{% bootstrap_field form.open  size='sm' %}

</div>
</form>

<div class="modal-footer">
{% block buttons %}
<button  type="button" data-form="#form-group-data" 
data-shell="#main-view" data-show="{% url 'group_app:create-group' organization_id %}"
class="btn btn-default e-post"> 
{% trans "Create" %}
</button>

{% endblock %}
</div>

group_app/templates/group_app/delete-group.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-remove"></span> Delete group 

{{group.name|truncatechars:60}}?
</div>

<div class="modal-body">
<p class="text-danger"> The content will no longer be avaiable!</p>

<form id="confirmGroupDeletionForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.name  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>

<div class="modal-footer">
<button type="button" class="btn btn-default" 
data-dismiss="modal">Cancel</button>

<button type="button" data-form="#confirmGroupDeletionForm"
data-shell="#main-view"  
data-show="{% url 'group_app:delete-group' group.id %}"
class="btn btn-danger e-post"> 
     {% trans "Delete" %}
</button>

group_app/templates/group_app/e-bind-group-user.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.peer.email}}"  data-content="{{event.user.description}}">
<span class="glyphicon glyphicon-user"></span>

{{event.peer.name}} </a> binded to

<a class="e-get"
data-shell="#main-view"
data-show="{% url 'group_app:list-posts' event.group.id %}" href="{{event.group.get_link_url}}"> 
<span class="glyphicon glyphicon-eye-open"></span> {{event.group.name}} </a>  

{% endblock %}

group_app/templates/group_app/e-create-group.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
Group
<a class="e-get"
data-shell="#main-view"
data-show="{% url 'group_app:list-posts' event.group.id %}"
href="{{event.group.get_link_url}}"> 
<span class="glyphicon glyphicon-eye-open"></span>
{{event.group.name}} </a> was created on 

<span class="glyphicon glyphicon-flag"></span>

{{event.organization.name}} 
{% endblock %}

group_app/templates/group_app/e-delete-group.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}

Group 
<span style="color:red"> 

<span class="glyphicon glyphicon-eye-open"></span>
{{event.group_name}} </span> was deleted 

{% endblock %}

group_app/templates/group_app/e-paste-post.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> has pasted

{% for ind in event.posts.all %}
<a class="e-get"
data-shell="#main-view"
data-show="{% url 'post_app:post' ind.id %}"
href="{{ind.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{ind.label}} {% if ind.task %} <b> *Task* </b> {% endif %}</a> 

{% endfor %}

on group 

<a class="e-get"
data-shell="#main-view"
data-show="{% url 'group_app:list-posts' event.group.id %}" href="{{event.group.get_link_url}}"> 
<span class="glyphicon glyphicon-eye-open"></span> {{event.group.name}} </a>   

{% endblock %}

group_app/templates/group_app/e-unbind-group-user.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}

Unser <a href="#" data-toggle="popover" data-trigger="hover" title="{{event.peer.email}}"  data-content="{{event.user.description}}">
<span style="color:red"> 
<span class="glyphicon glyphicon-user"></span>

{{event.peer.name}} </span> </a> was unbinded from

<a class="e-get"
data-shell="#main-view"
data-show="{% url 'group_app:list-posts' event.group.id %}" href="{{event.group.get_link_url}}"> 
<span class="glyphicon glyphicon-eye-open"></span> {{event.group.name}} </a>  

{% endblock %}

group_app/templates/group_app/e-update-group.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}

Group <a class="e-get"
data-shell="#main-view"
data-show="{% url 'group_app:list-posts' event.group.id %}" href="{{event.group.get_link_url}}"> 
<span class="glyphicon glyphicon-eye-open"></span>
{{event.group.name}} </a> was updated 

{% endblock %}

group_app/templates/group_app/event.html
{% load i18n %}
<p>

{% block content %}
{% endblock %}
</p>

<small>
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}">
<span class="glyphicon glyphicon-user"></span> {{event.user}} </a> on {{event.created}}
<a  href="#" data-show="{% url 'comment_app:list-comments' event.id %}"
class="text-info e-get"><span class="glyphicon glyphicon-comment"></span> 
Comment? </a>

</small>

group_app/templates/group_app/group.html
<div class="panel panel-default group" >

<div class="panel-body text-center">
<div class="pull-right"> <a class=" e-get text-default"  href="#" 
data-shell="#pins"  data-show="{% url 'group_app:pin-group' group.id %}">
<span class="glyphicon glyphicon-paperclip"></span> </a> </div>

<p> <a class="e-get" href="{{group.get_link_url}}" data-shell="#main-view" data-show="{% url 'group_app:list-posts' group.id %}" >
<span class="glyphicon glyphicon glyphicon-eye-open clip"></span> Group {{group.name}} 
<br>{{group.description}}</a></p>

<small>

<a href="#" data-toggle="popover" data-trigger="hover" title="{{group.owner.email}}"  data-content="{{group.owner.description}}">
{{group.owner.name}} </a> on <a href="{{group.get_link_url}}" target="_blank"> {{group.created}}</a>
</small>


</div>
</div>

group_app/templates/group_app/list-posts-scroll.html
{% load i18n %}

{% for ind in elems %}
<div id="post-{{ind.id}}">
        {% include 'post_app/post-data.html' with post=ind %}
</div>
{% endfor %}

<script>
$(document).ready(function() {
    $('[data-toggle="popover"]').popover();

});
</script>

group_app/templates/group_app/list-posts.html
{% load i18n %}

{% include 'board_app/list-pins.html' %}

{% include "group_app/list-posts-menu-group.html" %}
<br>

{{ elems | safe }}

group_app/templates/group_app/manage-group-users.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% load avatar %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
Available {{group.name|truncatechars:20}}'s Members 
<span class="badge">{{count}}/{{total}}</span>
</h5>
</div>

<div class="modal-body">

<div class="pre-scrollable">
{% for ind in included %}
<p class="text-center">
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}  
<br>

<small> {{ind.email}} </small>   <br>

<a class="r-post" style="color:red; font-size:70%" data-form="#userSearchForm"
data-show="{% url 'group_app:unbind-group-user' group.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> Unbind</a>  

</p>

{% endfor %}

{% for ind in excluded %}
<p class="text-center" >
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}  
<br>

<small> {{ind.email}} </small>  
<br>

<a class="r-post" style="color:green;font-size:70%" data-form="#userSearchForm"
data-show="{% url 'group_app:bind-group-user' group.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> Bind </a> 

</p>
{% endfor %}
</div>

<br>

<form id="userSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">

<button type="button" data-form="#userSearchForm" 
data-show="{% url 'group_app:manage-group-users' group.id  %}"
class="btn btn-default e-post"> {% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

group_app/templates/group_app/select-destin-group.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4>
<span class="glyphicon glyphicon-paperclip"></span>

Cards on Clipboard 
<span class="badge">{{total}}</span>
</h4>
</div>


<div class="modal-body">
<div class="pre-scrollable">
{% for ind in posts %}

<p> 
<span class="glyphicon glyphicon-file"></span>

{{ind.label|truncatechars:100}} 
<br>

<small>
<a class="e-get" data-show="{% url 'group_app:paste-post' group.id ind.id %} "
href="#"> <span class="glyphicon glyphicon-paste"></span> Paste</a>
</small>

</p>
{% empty %}
No posts.
{% endfor %}
</div>

</div>

<div class="modal-footer">
<script>
$('#mediumModal').one('hidden.bs.modal', function () {
    $('#main-view').load('{% url 'group_app:list-posts' group.id  %}');
})
</script>

<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

</div>