arcamens/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
# from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='site_app:index')),
     url(r'^core_app/', include('core_app.urls', namespace='core_app')), 
     url(r'^group_app/', include('group_app.urls', namespace='group_app')), 
     url(r'^board_app/', include('board_app.urls', namespace='board_app')), 
     url(r'^comment_app/', include('comment_app.urls', namespace='comment_app')), 
     url(r'^site_app/', include('site_app.urls', namespace='site_app')), 
     url(r'^cash_app/', include('cash_app.urls', namespace='cash_app')), 

     url(r'^post_app/', include('post_app.urls', namespace='post_app')), 
     url(r'^group_app/', include('group_app.urls', namespace='group_app')),
     url(r'^paybills/', include('paybills.urls', namespace='paybills')), 
     url(r'^onesignal/', include('onesignal.urls', namespace='onesignal')), 
    url(r'^board_app/', include('board_app.urls', namespace='board_app')),
    url(r'^card_app/', include('card_app.urls', namespace='card_app')),
    url(r'^snippet_app/', include('snippet_app.urls', namespace='snippet_app')),
    url(r'^note_app/', include('note_app.urls', namespace='note_app')),
    url(r'^jscroll/', include('jscroll.urls', namespace='jscroll')),

    url(r'^bitbucket_app/', include('bitbucket_app.urls', namespace='bitbucket_app')),
    url(r'^github_app/', include('github_app.urls', namespace='github_app')),

    url(r'^list_app/', include('list_app.urls', namespace='list_app')),

]


# handler500 = 'core_app.views.default_error'

card_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list-cards/(?P<list_id>.+)/', views.ListCards.as_view(), name='list-cards'),
    url(r'^cut-card/(?P<card_id>.+)/', views.CutCard.as_view(), name='cut-card'),
    url(r'^refresh-card-label/(?P<card_id>.+)/', views.RefreshCardLabel.as_view(), name='refresh-card-label'),

    url(r'^done/(?P<card_id>.+)/', views.Done.as_view(), name='done'),
    url(r'^undo/(?P<card_id>.+)/', views.Undo.as_view(), name='undo'),
    url(r'^archive-all/(?P<list_id>.+)/', views.ArchiveAll.as_view(), name='archive-all'),

    url(r'^card-worker-information/(?P<peer_id>.+)/(?P<card_id>.+)/', views.CardWorkerInformation.as_view(), name='card-worker-information'),
    url(r'^card-tag-information/(?P<tag_id>.+)/(?P<card_id>.+)/', views.CardTagInformation.as_view(), name='card-tag-information'),
    url(r'^card-link/(?P<card_id>.+)/', views.CardLink.as_view(), name='card-link'),
    url(r'^select-fork-list/(?P<card_id>.+)/', views.SelectForkList.as_view(), name='select-fork-list'),

    url(r'^create-card/(?P<ancestor_id>.+)/', views.CreateCard.as_view(), name='create-card'),

    url(r'^create-fork/(?P<ancestor_id>.+)/(?P<card_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    url(r'^pull-card-content/(?P<ancestor_id>.+)/(?P<card_id>.+)/', views.PullCardContent.as_view(), name='pull-card-content'),

    url(r'^attach-file/(?P<card_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^card-file-download/(?P<filewrapper_id>.+)/', views.CardFileDownload.as_view(), name='card-file-download'),

    url(r'^delete-card/(?P<card_id>.+)/', views.DeleteCard.as_view(), name='delete-card'),
    url(r'^view-data/(?P<card_id>.+)/', views.ViewData.as_view(), name='view-data'),
    url(r'^confirm-card-deletion/(?P<card_id>.+)/', views.ConfirmCardDeletion.as_view(), name='confirm-card-deletion'),
    url(r'^set-deadline/(?P<card_id>.+)/', views.SetDeadline.as_view(), name='set-deadline'),

    url(r'^update-card/(?P<card_id>.+)/', views.UpdateCard.as_view(), name='update-card'),
    url(r'^alert-card-workers/(?P<card_id>.+)/', views.AlertCardWorkers.as_view(), name='alert-card-workers'),


    url(r'^cut-card/(?P<card_id>.+)/', views.CutCard.as_view(), name='cut-card'),
    url(r'^copy-card/(?P<card_id>.+)/', views.CopyCard.as_view(), name='copy-card'),
    url(r'^setup-card-filter/(?P<list_id>.+)', views.SetupCardFilter.as_view(), name='setup-card-filter'),
    url(r'^manage-card-workers/(?P<card_id>.+)/', views.ManageCardWorkers.as_view(), name='manage-card-workers'),
    url(r'^bind-card-worker/(?P<card_id>.+)/(?P<user_id>.+)', views.BindCardWorker.as_view(), name='bind-card-worker'),
    url(r'^unbind-card-worker/(?P<card_id>.+)/(?P<user_id>.+)', views.UnbindCardWorker.as_view(), name='unbind-card-worker'),
    url(r'^pin-card/(?P<card_id>.+)/', views.PinCard.as_view(), name='pin-card'),
    url(r'^manage-card-tags/(?P<card_id>.+)/', views.ManageCardTags.as_view(), name='manage-card-tags'),
    url(r'^bind-card-tag/(?P<card_id>.+)/(?P<tag_id>.+)', views.BindCardTag.as_view(), name='bind-card-tag'),
    url(r'^unbind-card-tag/(?P<card_id>.+)/(?P<tag_id>.+)', views.UnbindCardTag.as_view(), name='unbind-card-tag'),
    url(r'^request-card-attention/(?P<peer_id>.+)/(?P<card_id>.+)', views.RequestCardAttention.as_view(), name='request-card-attention'),
    url(r'^find/', views.Find.as_view(), name='find'),
    url(r'^card-events/(?P<card_id>.+)/', views.CardEvents.as_view(), name='card-events'),
    url(r'^unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    url(r'^card-priority/(?P<card_id>.+)/', views.CardPriority.as_view(), name='card-priority'),

    url(r'^set-card-priority-down/(?P<card0_id>.+)/(?P<card1_id>.+)/', views.SetCardPriorityDown.as_view(), name='set-card-priority-down'),
    url(r'^set-card-priority-up/(?P<card0_id>.+)/(?P<card1_id>.+)/', views.SetCardPriorityUp.as_view(), name='set-card-priority-up'),
]

group_app/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    # url(r'^group/(?P<group_id>.+)/', views.Group.as_view(), name='group'),
    url(r'^list-posts/(?P<group_id>.+)/', views.ListPosts.as_view(), name='list-posts'),
    url(r'^create-group/(?P<organization_id>.+)', views.CreateGroup.as_view(), name='create-group'),
    url(r'^update-group/(?P<group_id>.+)/', views.UpdateGroup.as_view(), name='update-group'),
    url(r'^delete-group/(?P<group_id>.+)/', views.DeleteGroup.as_view(), name='delete-group'),
    url(r'^manage-user-groups/(?P<user_id>.+)/', views.ManageUserGroups.as_view(), name='manage-user-groups'),
    url(r'^manage-group-users/(?P<group_id>.+)/', views.ManageGroupUsers.as_view(), name='manage-group-users'),
    url(r'^bind-group-user/(?P<group_id>.+)/(?P<user_id>.+)/', views.BindGroupUser.as_view(), name='bind-group-user'),
    url(r'^unbind-group-user/(?P<group_id>.+)/(?P<user_id>.+)/', views.UnbindGroupUser.as_view(), name='unbind-group-user'),
    url(r'^bind-user-group/(?P<group_id>.+)/(?P<user_id>.+)/', views.BindUserGroup.as_view(), name='bind-user-group'),
    url(r'^unbind-user-group/(?P<group_id>.+)/(?P<user_id>.+)/', views.UnbindUserGroup.as_view(), name='unbind-user-group'),

    url(r'^group-link/(?P<group_id>.+)/', views.GroupLink.as_view(), name='group-link'),
    url(r'^pin-group/(?P<group_id>.+)/', views.PinGroup.as_view(), name='pin-group'),
    url(r'^unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    url(r'^select-destin-group/(?P<group_id>.+)/', views.SelectDestinGroup.as_view(), name='select-destin-group'),
    url(r'^paste-post/(?P<group_id>.+)/(?P<post_id>.+)/', views.PastePost.as_view(), name='paste-post'),
    url(r'^paste-all-posts/(?P<group_id>.+)/', views.PasteAllPosts.as_view(), name='paste-all-posts'),

]

post_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^post/(?P<post_id>.+)/', views.Post.as_view(), name='post'),
    url(r'^refresh-post/(?P<post_id>.+)/', views.RefreshPost.as_view(), name='refresh-post'),

    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),
    url(r'^alert-post-workers/(?P<post_id>.+)/', views.AlertPostWorkers.as_view(), name='alert-post-workers'),

    url(r'^done/(?P<post_id>.+)/', views.Done.as_view(), name='done'),
    url(r'^undo/(?P<post_id>.+)/', views.Undo.as_view(), name='undo'),

    url(r'^create-post/(?P<ancestor_id>.+)/', views.CreatePost.as_view(), name='create-post'),
    url(r'^update-post/(?P<post_id>.+)/', views.UpdatePost.as_view(), name='update-post'),
    url(r'^attach-file/(?P<post_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^post-file-download/(?P<filewrapper_id>.+)/', views.PostFileDownload.as_view(), name='post-file-download'),

    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),

    url(r'^post-worker-information/(?P<peer_id>.+)/(?P<post_id>.+)/', views.PostWorkerInformation.as_view(), name='post-worker-information'),
    url(r'^post-tag-information/(?P<tag_id>.+)/(?P<post_id>.+)/', views.PostTagInformation.as_view(), name='post-tag-information'),

    url(r'^manage-post-workers/(?P<post_id>.+)/', views.ManagePostWorkers.as_view(), name='manage-post-workers'),
    url(r'^assign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.AssignPostUser.as_view(), name='assign-post-user'),
    url(r'^unassign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.UnassignPostUser.as_view(), name='unassign-post-user'),
    url(r'^setup-post-filter/(?P<group_id>.+)', views.SetupPostFilter.as_view(), name='setup-post-filter'),
    url(r'^find/', views.Find.as_view(), name='find'),

    url(r'^cut-post/(?P<post_id>.+)/', views.CutPost.as_view(), name='cut-post'),
    url(r'^copy-post/(?P<post_id>.+)/', views.CopyPost.as_view(), name='copy-post'),
    url(r'^manage-post-tags/(?P<post_id>.+)/', views.ManagePostTags.as_view(), name='manage-post-tags'),
    url(r'^bind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.BindPostTag.as_view(), name='bind-post-tag'),
    url(r'^unbind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.UnbindPostTag.as_view(), name='unbind-post-tag'),
    url(r'^request-post-attention/(?P<peer_id>.+)/(?P<post_id>.+)', views.RequestPostAttention.as_view(), name='request-post-attention'),
    url(r'^confirm-post-deletion/(?P<post_id>.+)/', views.ConfirmPostDeletion.as_view(), name='confirm-post-deletion'),
    url(r'^select-fork-list/(?P<post_id>.+)/', views.SelectForkList.as_view(), name='select-fork-list'),
    url(r'^create-post-fork/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.CreatePostFork.as_view(), name='create-post-fork'),
    url(r'^pull-card-content/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.PullCardContent.as_view(), name='pull-card-content'),
    url(r'^post-events/(?P<post_id>.+)/', views.PostEvents.as_view(), name='post-events'),
    url(r'^pin-post/(?P<post_id>.+)/', views.PinPost.as_view(), name='pin-post'),
    url(r'^unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    url(r'^set-post-priority-down/(?P<post0_id>.+)/(?P<post1_id>.+)/', views.SetPostPriorityDown.as_view(), name='set-post-priority-down'),
    url(r'^set-post-priority-up/(?P<post0_id>.+)/(?P<post1_id>.+)/', views.SetPostPriorityUp.as_view(), name='set-post-priority-up'),
    url(r'^post-priority/(?P<post_id>.+)/', views.PostPriority.as_view(), name='post-priority'),

]

snippet_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create-snippet/(?P<post_id>.+)/', views.CreateSnippet.as_view(), name='create-snippet'),
    url(r'^update-snippet/(?P<snippet_id>.+)/', views.UpdateSnippet.as_view(), name='update-snippet'),
    url(r'^snippet/(?P<snippet_id>.+)/', views.Snippet.as_view(), name='snippet'),
    url(r'^delete-snippet/(?P<snippet_id>.+)/', views.DeleteSnippet.as_view(), name='delete-snippet'),

    url(r'^attach-file/(?P<snippet_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^snippet-file-download/(?P<filewrapper_id>.+)/', views.SnippetFileDownload.as_view(), name='snippet-file-download'),

    url(r'^snippet-link/(?P<snippet_id>.+)/', views.SnippetLink.as_view(), name='snippet-link'),

]

post_app/forms.py
from django import forms
from sqlike.forms import SqLikeForm
from core_app.forms import FileAttachment
from . import models

class PostForm(forms.ModelForm):
    class Meta:
        model  = models.Post
        exclude = ('user', 'ancestor', 'html', 'parent', 'priority')

class PostFileWrapperForm(FileAttachment, forms.ModelForm):
    class Meta:
        model  = models.PostFileWrapper
        exclude = ('post', )

class PostFilterForm(SqLikeForm, forms.ModelForm):
    class Meta:
        model  = models.PostFilter
        exclude = ('user', 'group')

class GlobalPostFilterForm(SqLikeForm, forms.ModelForm):
    class Meta:
        model  = models.GlobalPostFilter
        exclude = ('user', 'organization')

class UserSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False,
    help_text='Example: oliveira + mens.com')

class TagSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False, 
    help_text='Example: feature')

class PostAttentionForm(forms.Form):
    message = forms.CharField(
    required=False, widget=forms.Textarea,
    help_text='(Optional) Be in the meeting 20 min earlier.')

class AlertPostWorkersForm(forms.Form):
    message = forms.CharField(
    required=False, widget=forms.Textarea,
    help_text='Please, take a look at this asap!')

class ListSearchform(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False, 
    help_text='Ex: arcamens + todo ...')

class PostPriorityForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False, 
    help_text='Example: owner:oliveira + tag:bug')

post_app/templates/post_app/e-bind-tag-post.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
Post <a class="e-get"
data-shell="#main-view"
data-show="{% url 'post_app:post' event.post.id %}" href="{{event.post.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.post.label}} </a>  

was tagged with {{event.tag.name}} on group 

<a class="e-get" data-shell="#main-view"
data-show="{% url 'group_app:list-posts' event.ancestor.id %}" href="{{event.ancestor.get_link_url}}"> 
<span class="glyphicon glyphicon-eye-open"></span> {{event.ancestor.name}} 
</a>

{% endblock %}

post_app/templates/post_app/e-copy-post.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
Post <a class="e-get"
data-shell="#main-view"
data-show="{% url 'post_app:post' event.post.id %}"
href="{{event.post.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.post.label}} </a>

was copied from group

<a class="e-get"
data-shell="#main-view"
data-show="{% url 'group_app:list-posts' event.group.id %}" href="{{event.group.get_link_url}}"> 
<span class="glyphicon glyphicon-eye-open"></span> {{event.group.name}} </a>  
{% endblock %}

post_app/templates/post_app/manage-post-workers.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% load avatar %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
Available {{post.label|truncatechars:"60"}}'s Workers 
<span class="badge">{{count}}/{{total}}</span>
</h5>
</div>

<div class="modal-body">
<div class="pre-scrollable">
{% for ind in included %}
<p class="text-center">
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}  
<br>

<small> {{ind.email}} </small>   <br>

<a class="r-post" style="color:red; font-size:70%" data-form="#userSearchForm" data-callback="refreshPost();"
data-show="{% url 'post_app:unassign-post-user' post.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> Unbind</a>  

</p>

{% endfor %}

{% for ind in excluded %}
<p class="text-center" >
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}  
<br>

<small> {{ind.email}} </small>  
<br>

<a class="r-post" style="color:green;font-size:70%" data-form="#userSearchForm" data-callback="refreshPost();"
data-show="{% url 'post_app:assign-post-user' post.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> bind </a> 

</p>
{% endfor %}
</div>

<br> 

<form id="userSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">
<script>
function refreshPost() {
    $('#post-{{post.id}}').load('{% url 'post_app:refresh-post' post.id  %}');
}
</script>

<button  type="button" data-form="#userSearchForm" 
data-show="{% url 'post_app:manage-post-workers' post.id  %}"
class="btn btn-default e-post"> {% trans "Filter" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

post_app/templates/post_app/post-data.html
{% load i18n %}
{% load static %}

<div class="panel panel-default" >
<div class="panel-heading clearfix" > 

<div style="word-wrap: break-word;"> 
<span class="glyphicon glyphicon-file"></span>

{% if post.done %} (Done) {% endif %} Post by  <a href="#" data-toggle="popover" data-trigger="hover" title="{{post.user.email}}"  data-content="{{post.user.description}}">
{{post.user.name}} </a> 
on group

<a class="e-get" href="{{post.ancestor.get_link_url}}"
data-show="{% url 'group_app:list-posts' post.ancestor.id %}"
data-shell="#main-view" > 
<span class="glyphicon glyphicon-eye-open"></span> {{post.ancestor.name}} </a>

on <a href="{% url 'post_app:post-link' post.id %}" target="_blank"> {{post.created}} </a>
<div class="pull-right">
<a class=" e-get text-default"  href="#" data-shell="#pins"  data-show="{% url 'post_app:pin-post' post.id %}">
<span class="glyphicon glyphicon-paperclip"></span> </a>
</div>


</div>


</div>

<div class="panel-body" >
<div style="word-wrap: break-word;"> 

<h5> {{post.label}} </h5>

{{post.html|safe}}

</div>

{% for ind in post.snippets.all %}
<a data-show="{% url 'snippet_app:snippet' ind.id %}" class="e-get"  data-shell="#bigModalContent" href="{{ind.get_link_url}}"> 
<span class="glyphicon glyphicon-book"></span> {{ind.title}} </a>
{% empty %}
No snippets...
{% endfor %}

<hr>
<span style="font-size:80%">
<!-- Add a min-height so it doesnt get relayout -->
<div id="post-attachments-{{post.id}}" style="min-height:52px;"> </div>
<script> 

$.get({ 
url: "{% url 'post_app:attach-file' post.id %}",
async: true},

function(data) {
    $('#post-attachments-{{post.id}}').html(data);
});

</script>
</span>

<div class="row">

<div class="col-md-3">
<h5> <span class="glyphicon glyphicon-tag"></span> Tags </h5>
<div class="pre-scrollable" style="font-size:90%">

{% for ind in post.tags.all %}
<a 
data-show="{% url 'post_app:post-tag-information' ind.id post.id %}"
data-shell="#smallModalContent" 
class="e-get"
href="#">
<span class="glyphicon glyphicon-tag"></span>

{{ind.name}}
</a>

{% empty %}
No tags.
{% endfor %} </div> </div>

<div class="col-md-3">
<h5> 
<span class="glyphicon glyphicon-user"></span>

Workers </h5>

<div class="pre-scrollable" style="font-size:90%">
{% for ind in post.workers.all %}
<a 
data-show="{% url 'post_app:post-worker-information' ind.id post.id %}"
data-shell="#smallModalContent" 
class="e-get"
href="#">
<span class="glyphicon glyphicon-user"></span>

{{ind.name}}
</a>

{% if forloop.last %} 
<br> <a class="e-get text-warning" data-shell="#smallModalContent"  
data-show="{% url 'post_app:alert-post-workers' post.id %}" href="#">
<span class="glyphicon glyphicon-alert"></span>

Alert workers?</a>

{% endif %}

{% empty %}
No workers.
{% endfor %}
</div></div>

<div class="col-md-6">
<h5> <span class="glyphicon glyphicon-random"></span> Forks </h5>

<div class="pre-scrollable" style="font-size:90%">
{% for ind in post.card_forks.all %}
<a href="{{ind.get_link_url}}" class="e-get" data-shell="#bigModalContent" data-show="{{ind.get_absolute_url}}" >
<span class="glyphicon glyphicon-file"></span> {% if ind.done %} (Done) {% endif %} {{ind.label|truncatechars:80}} </a> 
<br>
{% empty %}
No forks.
{% endfor %}</div></div>


</div> 

</div>



<div class="panel-footer">
{% block footer %}

<a data-show="{% url 'post_app:update-post' post.id %}" data-shell="#bigModalContent"  href="#" class="e-get"> 
<span class="glyphicon glyphicon-edit"></span> Update</a>

<a href="#"
data-shell="#smallModalContent" data-show="{% url 'post_app:manage-post-workers' post.id %}"
class="e-get"><span class="glyphicon glyphicon-user"> </span> Assign </a>

<a class="e-get text-danger" data-shell="#smallModalContent" href="#" data-show="{% url 'post_app:confirm-post-deletion' post.id %}">
<span class="glyphicon glyphicon-remove"></span> Delete  </a>

{% if post.done %}
<a href="#" data-shell="#post-{{post.id}}" data-show="{% url 'post_app:undo' post.id %}"
class="text-warning  e-get"><span class="glyphicon glyphicon-ok"></span> Undo </a>

{% else %}

<a href="#" data-shell="#post-{{post.id}}" data-show="{% url 'post_app:done' post.id %}"
class="text-warning e-get"><span class="glyphicon glyphicon-ok"></span> Done </a>
{% endif %}

<a  data-shell="#bigModalContent" class="e-get text-info" data-show="{% url 'snippet_app:create-snippet' post.id %}" 
href="#"><span class="glyphicon glyphicon-plus"></span> Snippet</a>

<a class="e-get"  href="#"
data-shell="#main-view" data-show="{% url 'post_app:copy-post' post.id %}">
<span class="glyphicon glyphicon-copy"></span> Copy </a>

<a class="text-warning e-get" href="#"
data-shell="#main-view" data-show="{% url 'post_app:cut-post' post.id %}">
<span class="glyphicon glyphicon-scissors"></span> Cut </a>

<a href="#"
data-shell="#smallModalContent" data-show="{% url 'post_app:manage-post-tags' post.id %}"
class="e-get"><span class="glyphicon glyphicon-tag"></span> Tags </a>

<a class="e-get" href="#" data-shell="#smallModalContent"
data-show="{% url 'post_app:select-fork-list' post.id %}">
<span class="glyphicon glyphicon-random"></span> Fork </a>

<a class="e-get" href="#" data-shell="#mediumModalContent" data-show="{% url 'post_app:post-events' post.id %}"> 
<span class="glyphicon glyphicon-bell"></span> E/C</a>

<div class="pull-right">
<a  data-shell="#bigModalContent" class="e-get text-default"  href="#" data-show="{% url 'post_app:post-priority' post.id %}">
<span class="glyphicon glyphicon-signal"></span> </a>
</div>


{% endblock %}
</div>
</div>

post_app/templates/post_app/post-priority.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span> {{post.label|truncatechars:60}}'s Priority
<span class="badge">{{count}}/{{total}}</span> </h5>
</div>

<div class="modal-body">
<div class="pre-scrollable">

{% for ind in posts %}
<p>


<a href="{{ind.get_link_url}}" target="_blank"> {{ind.label}}</a> 
<br>

<small>
<a class="e-get text-danger"  data-shell="#main-view"  
data-show="{% url 'post_app:set-post-priority-up' post.id ind.id %}" href="{{ind.get_link_url}}">  <span class="glyphicon glyphicon-arrow-up"></span>Up</a> 

<a class="e-get text-success" data-shell="#main-view"  
data-show="{% url 'post_app:set-post-priority-down' post.id ind.id %}" href="{{ind.get_link_url}}">  <span class="glyphicon glyphicon-arrow-down"></span>Down</a> 
</small>

</p>
{% endfor %}

</div> <br>
<form id="postPriorityForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>

</div>

<div class="modal-footer">

<button type="button" class="btn btn-default" 
data-dismiss="modal">Close</button>

<button  type="button" data-form="#postPriorityForm" 
id="filterCardRelations" data-show="{% url 'post_app:post-priority' post.id  %}"
class="btn btn-default e-post"> {% trans "Search" %} </button>

</div>