arcamens/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
# from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='site_app:index')),
     url(r'^core_app/', include('core_app.urls', namespace='core_app')), 
     url(r'^group_app/', include('group_app.urls', namespace='group_app')), 
     url(r'^board_app/', include('board_app.urls', namespace='board_app')), 
     url(r'^comment_app/', include('comment_app.urls', namespace='comment_app')), 
     url(r'^site_app/', include('site_app.urls', namespace='site_app')), 
     url(r'^cash_app/', include('cash_app.urls', namespace='cash_app')), 

     url(r'^post_app/', include('post_app.urls', namespace='post_app')), 
     url(r'^group_app/', include('group_app.urls', namespace='group_app')),
     url(r'^paybills/', include('paybills.urls', namespace='paybills')), 
     url(r'^onesignal/', include('onesignal.urls', namespace='onesignal')), 
    url(r'^board_app/', include('board_app.urls', namespace='board_app')),
    url(r'^card_app/', include('card_app.urls', namespace='card_app')),
    url(r'^snippet_app/', include('snippet_app.urls', namespace='snippet_app')),
    url(r'^note_app/', include('note_app.urls', namespace='note_app')),
    url(r'^jscroll/', include('jscroll.urls', namespace='jscroll')),

    url(r'^bitbucket_app/', include('bitbucket_app.urls', namespace='bitbucket_app')),
    url(r'^github_app/', include('github_app.urls', namespace='github_app')),

    url(r'^list_app/', include('list_app.urls', namespace='list_app')),

]


# handler500 = 'core_app.views.default_error'

card_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list-cards/(?P<list_id>.+)/', views.ListCards.as_view(), name='list-cards'),
    url(r'^cut-card/(?P<card_id>.+)/', views.CutCard.as_view(), name='cut-card'),
    url(r'^refresh-card-label/(?P<card_id>.+)/', views.RefreshCardLabel.as_view(), name='refresh-card-label'),

    url(r'^done/(?P<card_id>.+)/', views.Done.as_view(), name='done'),
    url(r'^undo/(?P<card_id>.+)/', views.Undo.as_view(), name='undo'),
    url(r'^archive-all/(?P<list_id>.+)/', views.ArchiveAll.as_view(), name='archive-all'),

    url(r'^card-worker-information/(?P<peer_id>.+)/(?P<card_id>.+)/', views.CardWorkerInformation.as_view(), name='card-worker-information'),
    url(r'^card-tag-information/(?P<tag_id>.+)/(?P<card_id>.+)/', views.CardTagInformation.as_view(), name='card-tag-information'),
    url(r'^card-link/(?P<card_id>.+)/', views.CardLink.as_view(), name='card-link'),
    url(r'^select-fork-list/(?P<card_id>.+)/', views.SelectForkList.as_view(), name='select-fork-list'),

    url(r'^create-card/(?P<ancestor_id>.+)/', views.CreateCard.as_view(), name='create-card'),

    url(r'^create-fork/(?P<ancestor_id>.+)/(?P<card_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    url(r'^pull-card-content/(?P<ancestor_id>.+)/(?P<card_id>.+)/', views.PullCardContent.as_view(), name='pull-card-content'),

    url(r'^attach-file/(?P<card_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^card-file-download/(?P<filewrapper_id>.+)/', views.CardFileDownload.as_view(), name='card-file-download'),

    url(r'^delete-card/(?P<card_id>.+)/', views.DeleteCard.as_view(), name='delete-card'),
    url(r'^view-data/(?P<card_id>.+)/', views.ViewData.as_view(), name='view-data'),
    url(r'^confirm-card-deletion/(?P<card_id>.+)/', views.ConfirmCardDeletion.as_view(), name='confirm-card-deletion'),
    url(r'^set-deadline/(?P<card_id>.+)/', views.SetDeadline.as_view(), name='set-deadline'),

    url(r'^update-card/(?P<card_id>.+)/', views.UpdateCard.as_view(), name='update-card'),
    url(r'^alert-card-workers/(?P<card_id>.+)/', views.AlertCardWorkers.as_view(), name='alert-card-workers'),


    url(r'^cut-card/(?P<card_id>.+)/', views.CutCard.as_view(), name='cut-card'),
    url(r'^copy-card/(?P<card_id>.+)/', views.CopyCard.as_view(), name='copy-card'),
    url(r'^setup-card-filter/(?P<list_id>.+)', views.SetupCardFilter.as_view(), name='setup-card-filter'),
    url(r'^manage-card-workers/(?P<card_id>.+)/', views.ManageCardWorkers.as_view(), name='manage-card-workers'),
    url(r'^bind-card-worker/(?P<card_id>.+)/(?P<user_id>.+)', views.BindCardWorker.as_view(), name='bind-card-worker'),
    url(r'^unbind-card-worker/(?P<card_id>.+)/(?P<user_id>.+)', views.UnbindCardWorker.as_view(), name='unbind-card-worker'),
    url(r'^pin-card/(?P<card_id>.+)/', views.PinCard.as_view(), name='pin-card'),
    url(r'^manage-card-tags/(?P<card_id>.+)/', views.ManageCardTags.as_view(), name='manage-card-tags'),
    url(r'^bind-card-tag/(?P<card_id>.+)/(?P<tag_id>.+)', views.BindCardTag.as_view(), name='bind-card-tag'),
    url(r'^unbind-card-tag/(?P<card_id>.+)/(?P<tag_id>.+)', views.UnbindCardTag.as_view(), name='unbind-card-tag'),
    url(r'^request-card-attention/(?P<peer_id>.+)/(?P<card_id>.+)', views.RequestCardAttention.as_view(), name='request-card-attention'),
    url(r'^find/', views.Find.as_view(), name='find'),
    url(r'^card-events/(?P<card_id>.+)/', views.CardEvents.as_view(), name='card-events'),
    url(r'^unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    url(r'^card-priority/(?P<card_id>.+)/', views.CardPriority.as_view(), name='card-priority'),

    url(r'^set-card-priority-down/(?P<card0_id>.+)/(?P<card1_id>.+)/', views.SetCardPriorityDown.as_view(), name='set-card-priority-down'),
    url(r'^set-card-priority-up/(?P<card0_id>.+)/(?P<card1_id>.+)/', views.SetCardPriorityUp.as_view(), name='set-card-priority-up'),
]

note_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create-note/(?P<card_id>.+)/', views.CreateNote.as_view(), name='create-note'),
    url(r'^list-notes/(?P<card_id>.+)/', views.ListNotes.as_view(), name='list-notes'),
    url(r'^note-link/(?P<note_id>.+)/', views.NoteLink.as_view(), name='note-link'),

    url(r'^update-note/(?P<note_id>.+)/', views.UpdateNote.as_view(), name='update-note'),
    url(r'^preview-note/(?P<note_id>.+)/', views.PreviewNote.as_view(), name='preview-note'),

    url(r'^note/(?P<note_id>.+)/', views.Note.as_view(), name='note'),
    url(r'^delete-note/(?P<note_id>.+)/', views.DeleteNote.as_view(), name='delete-note'),

    url(r'^attach-file/(?P<note_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^note-file-download/(?P<filewrapper_id>.+)/', views.NoteFileDownload.as_view(), name='note-file-download'),
]

note_app/forms.py
from core_app.forms import FileAttachment
from django import forms
from . import models

class NoteForm(forms.ModelForm):
    data = forms.CharField(strip=False, widget=forms.Textarea)
    class Meta:
        model  = models.Note
        exclude = ('card', 'owner')

class NoteFileWrapperForm(FileAttachment, forms.ModelForm):
    class Meta:
        model  = models.NoteFileWrapper
        exclude = ('note', )

note_app/views.py
from django.views.generic import View
from django.conf import settings
from django.db.models import Q
from django.shortcuts import render, redirect
from core_app.views import GuardianView, FileDownload

from django.http import HttpResponse
from card_app.models import Card
from core_app.models import User
from . import models
from . import forms

class Note(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        attachments = note.notefilewrapper_set.all()

        return render(request, 'note_app/note.html', 
        {'note': note, 'attachments': attachments})

class NoteLink(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        organizations = self.me.organizations.exclude(id=self.me.default.id)

        return render(request, 'note_app/note-link.html', 
        {'note': note, 'card': note.card, 'user': self.me, 
        'organizations': organizations, 'default': self.me.default, 
        'organization': self.me.default, 'settings': settings})

class ListNotes(GuardianView):
    def get(self, request, card_id):
        card = Card.locate(self.me, self.me.default, card_id)
        notes = card.notes.all().order_by('-created')

        return render(request, 'note_app/list-notes.html', 
        {'records': notes, 'card': card})

class CreateNote(GuardianView):
    """
    """

    def get(self, request, card_id):
        card = Card.locate(self.me, self.me.default, card_id)
        form = forms.NoteForm()
        return render(request, 'note_app/create-note.html', 
        {'form':form, 'card': card})

    def post(self, request, card_id):
        card = Card.locate(self.me, self.me.default, card_id)
        form = forms.NoteForm(request.POST)
        user = User.objects.get(id=self.user_id)

        if not form.is_valid():
            return render(request, 'note_app/create-note.html', 
                {'form': form, 'card':card}, status=400)

        note       = form.save(commit=False)
        note.owner = self.me
        note.card  = card
        note.save()

        event = models.ECreateNote.objects.create(
        organization=self.me.default, child=card, user=self.me, note=note)
        event.dispatch(*card.ancestor.ancestor.members.all())

        return render(request, 'note_app/preview-note.html',
        {'note': note, 'card': note.card})

class AttachFile(GuardianView):
    """
    """

    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        attachments = note.notefilewrapper_set.all()
        form = forms.NoteFileWrapperForm()

        return render(request, 'note_app/attach-file.html', 
        {'note':note, 'form': form, 'attachments': attachments})

    def post(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        note = models.Note.objects.get(id=note_id)
        attachments = note.notefilewrapper_set.all()

        form = forms.NoteFileWrapperForm(request.POST, 
        request.FILES, user=self.me)

        if not form.is_valid():
            return render(request, 'note_app/attach-file.html', 
                {'note':note, 'form': form, 'attachments': attachments})
        record = form.save(commit = False)
        record.organization = self.me.default
        record.note = note
        form.save()

        event = models.EAttachNoteFile.objects.create(
        organization=self.me.default, filewrapper=record, 
        note=note, user=self.me)

        event.dispatch(*note.card.ancestor.ancestor.members.all())
        event.save()

        return self.get(request, note_id)

class DetachFile(GuardianView):
    """
    """

    def get(self, request, filewrapper_id):
        filewrapper = models.NoteFileWrapper.objects.filter(
        Q(note__card__ancestor__ancestor__members=self.me) | Q(note__card__workers=self.me), 
        note__card__ancestor__ancestor__organization=self.me.default, 
        id=filewrapper_id).distinct().first()

        attachments = filewrapper.note.notefilewrapper_set.all()
        form        = forms.NoteFileWrapperForm()

        event = models.EDettachNoteFile.objects.create(
        organization=self.me.default, filename=filewrapper.file.name, 
        note=filewrapper.note, user=self.me)

        event.dispatch(*filewrapper.note.card.ancestor.ancestor.members.all())
        event.save()
        filewrapper.delete()

        return render(request, 'note_app/attach-file.html', 
        {'note':filewrapper.note, 'form': form, 'attachments': attachments})

class PreviewNote(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        
        return render(request, 'note_app/preview-note.html',
        {'note': note, 'card': note.card})

class UpdateNote(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)
        return render(request, 'note_app/update-note.html',
        {'note': note, 'form': forms.NoteForm(instance=note),})

    def post(self, request, note_id):
        record = models.Note.locate(self.me, self.me.default, note_id)
        form    = forms.NoteForm(request.POST, instance=record)

        if not form.is_valid():
            return render(request, 'note_app/update-note.html',
                        {'form': form, 'note':record, }, status=400)

        record.save()

        event = models.EUpdateNote.objects.create(
        organization=self.me.default, child=record.card, 
        note=record, user=self.me)

        event.dispatch(*record.card.ancestor.ancestor.members.all())
        event.save()

        # user.ws_sound(record.card.ancestor.ancestor)

        return redirect('note_app:preview-note', 
        note_id=record.id)

class DeleteNote(GuardianView):
    def get(self, request, note_id):
        note = models.Note.locate(self.me, self.me.default, note_id)

        event = models.EDeleteNote.objects.create(organization=self.me.default,
        child=note.card, note='Note', user=self.me)

        event.dispatch(*note.card.ancestor.ancestor.members.all())
        note.delete()

        # user.ws_sound(note.card.ancestor.ancestor)

        return redirect('note_app:list-notes', 
        card_id=note.card.id)

class NoteFileDownload(FileDownload):
    def get(self, request, filewrapper_id):
        filewrapper = models.NoteFileWrapper.objects.filter(
        Q(note__card__ancestor__ancestor__members=self.me) | Q(note__card__workers=self.me), 
        note__card__ancestor__ancestor__organization=self.me.default, 
        id=filewrapper_id).distinct().first()

        return self.get_file_url(filewrapper.file)

note_app/templates/note_app/attach-file.html
{% load bootstrap3 %}
{% load i18n %}
{% load bname %}

<script>
$('#NoteFileWrapperForm-{{note.id}}').change(function(){
   var formData = new FormData($('#NoteFileWrapperForm-{{note.id}}')[0]);

   $.ajax({
   url: "{% url 'note_app:attach-file' note.id  %}", 
   type: 'POST',
   success: function(data) {
   $('#note-attachments-{{note.id}}').html(data);},
   data: formData,
   cache: false,
   contentType: false,
   processData: false});
});

</script>

<form id="NoteFileWrapperForm-{{note.id}}" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.file  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>

{% for ind in attachments %}
<a class="e-get text-danger" data-shell="#note-attachments-{{note.id}}" href="#"
data-show="{% url 'note_app:detach-file' ind.id %}"> 
<span class="glyphicon glyphicon-remove"></span></a> 

<a href="{% url 'note_app:note-file-download' ind.id %}" target="_blank"> {{ind.file.name|bname}} </a>
{% empty %}
No attachments.
{% endfor %}

note_app/templates/note_app/create-note.html
{% load bootstrap3 %}
{% load i18n %}

<form id="form-note-data" enctype="multipart/form-data">

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4> 
<span class="glyphicon glyphicon glyphicon-comment"></span>
 Note </h4>
</div>

<div class="modal-body">

{% csrf_token %}

{% bootstrap_field form.data  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}

</div>
</form>


<div class="modal-footer">
{% block buttons %}

<button  type="button" data-show="{% url 'note_app:list-notes' card.id %}"
class="btn btn-default e-get"> 
     {% trans "Back" %}
</button>

<button  type="button" data-form="#form-note-data" 
data-show="{% url 'note_app:create-note' card.id %}"
class="btn btn-default e-post"> 
     {% trans "Create" %}
</button>
{% endblock %}
</div>

note_app/templates/note_app/e-attach-note-file.html
{% extends 'group_app/event.html' %}
{% load i18n %}
{% load bname %}

{% block content %}
File <a href="{% url 'note_app:note-file-download' event.filewrapper.id %}" target="_blank"> {{event.filewrapper.file.name|bname}} </a>

was attached to 

<a class="e-get"
data-shell="#bigModalContent" 
data-show="{% url 'note_app:preview-note' event.note.id %}" 
href="{{event.note.get_link_url}}"> 
<span class="glyphicon glyphicon-book"></span> Note </a> 

{% endblock %}

note_app/templates/note_app/e-create-note.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> has created a

<a class="e-get"
data-shell="#bigModalContent" 
data-show="{% url 'note_app:preview-note' event.note.id %}" 
href="{{event.note.get_link_url}}"> 
<span class="glyphicon glyphicon-book"></span> Note </a> 

on card

<a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'card_app:view-data' event.child.id %}" 
href="{{event.child.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.child.label|truncatechars:40}} </a> 

{% endblock %}

note_app/templates/note_app/e-delete-note.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> has deleted 

<span style="color:red">
<span class="glyphicon glyphicon-book"></span> Note 
</span>

on

<a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'card_app:view-data' event.child.id %}" 
href="{{event.child.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.child.label|truncatechars:40}} </a> 

{% endblock %}

note_app/templates/note_app/e-dettach-note-file.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}">
<span class="glyphicon glyphicon-user"></span>

{{event.user}} </a> has dettached file <span class="text-danger"> 
<span class="glyphicon glyphicon-file"></span>

{{event.filename}}</span>  from 

<a class="e-get"
data-shell="#bigModalContent" 
data-show="{% url 'note_app:preview-note' event.note.id %}" 
href="{{event.note.get_link_url}}"> 
<span class="glyphicon glyphicon-book"></span> Note </a> 

{% endblock %}

note_app/templates/note_app/e-update-note.html
{% extends 'group_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.description}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> has updated a 

<a class="e-get"
data-shell="#bigModalContent" 
data-show="{% url 'note_app:preview-note' event.note.id %}" 
href="{{event.note.get_link_url}}"> 
<span class="glyphicon glyphicon-book"></span> Note </a> 

on

<a class="e-get"
data-shell="#bigModalContent"
data-show="{% url 'card_app:view-data' event.child.id %}" 
href="{{event.child.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.child.label|truncatechars:40}} </a> 

{% endblock %}

note_app/templates/note_app/list-notes.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>

<h5 class="modal-title">
<span class="glyphicon glyphicon-comment"></span>
Notes on card <span class="glyphicon glyphicon-file"></span> {{card.label|truncatechars:60}} 

<span class="badge">{{records.count}}</span>
</h5>
</div>

<div class="modal-body pre-scrollable">

{% for ind in records %}
{% include 'note_app/note.html' with note=ind %}
{% endfor %}

</div>
<div class="modal-footer" >
<button  type="button" data-shell="#bigModalContent" 
data-show="{% url 'card_app:view-data' card.id %}"
class="btn btn-default e-get"> {% trans "Back" %} </button>

<button  type="button" 
data-show="{% url 'note_app:create-note' card.id %}"
data-shell="#bigModalContent" 
class="btn btn-default e-get"> {% trans "Create" %} </button>

<script>
$(function () {
    $('[data-toggle="popover"]').popover()
})
</script>

</div>

note_app/templates/note_app/note-link.html
{% extends 'core_app/index.html' %}

{% load i18n %}
{% load static %}

{% block initializer %}
<script>
$(document).ready(function() {
    $('#main-view').load("{% url 'card_app:list-cards' card.ancestor.id %}");
    $('#bigModalContent').load("{% url 'note_app:preview-note' note.id %}");
    $('#bigModal').modal('show');

});

$(function () {
    $('[data-toggle="popover"]').popover()
})
</script>
{% endblock %}

note_app/templates/note_app/note-menu-actions.html
<div class="dropdown">
  <a class="dropdown-toggle" type="button" data-toggle="dropdown">
  <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="#">Update</a></li>
    <li><a href="#">Remove</a></li>
  </ul>
</div>

note_app/templates/note_app/note.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}

<div class="panel panel-default">
  <div class="panel-body">

<p style="font-size:80%"> 
<span class="glyphicon glyphicon-comment"></span> 

By 
<a href="#" data-toggle="popover" data-trigger="hover" title="{{note.owner.email}}"  data-content="{{note.owner.description}}"> {{note.owner.name}} </a>
on <a href="{{note.get_link_url}}" target="_blank"> {{note.created}} </a>

</p>

<div style="word-wrap: break-word;"> 

{{note.html | safe}}

</div>

<span  style="font-size:80%">
<div id="note-attachments-{{note.id}}" style="min-height:50px;"> </div>

<script> 
$.get({ 
url: "{% url 'note_app:attach-file' note.id %}",
async: true},

function(data) {
    $('#note-attachments-{{note.id}}').html(data);
});
</script> 

</span>

<br>

<a href="#"
data-show="{% url 'note_app:update-note' note.id %}"
data-shell="#bigModalContent" 
class="text-warning e-get"> 
<span class="glyphicon glyphicon-edit"></span> 
{% trans "Update" %} </a>

<a href="#"
data-show="{% url 'note_app:delete-note' note.id %}"
data-shell="#bigModalContent" 
class="text-danger e-get"> 
<span class="glyphicon glyphicon-remove"></span> 

{% trans "Remove" %} </a>

</div>


</div>

note_app/templates/note_app/preview-note.html
{% load bootstrap3 %}
{% load static %}

{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-comment"></span> 
Note on card 

<a href="{{card.get_link_url}}" data-shell="#bigModalContent" data-show="{% url 'card_app:view-data' card.id %}"
class="e-get">  <span class="glyphicon glyphicon-file"></span> {{card.label|truncatechars:60}} </a>

</div>

<div class="modal-body pre-scrollable">
{% include 'note_app/note.html' %}
</div>

<div class="modal-footer" >
<button  type="button" 
data-show="{% url 'note_app:list-notes' card.id %}"
data-shell="#bigModalContent" 
class="btn btn-default e-get"> {% trans "Notes" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

note_app/templates/note_app/update-note.html
{% extends "note_app/create-note.html" %}
{% load i18n %}
{% block title %}
<span class="glyphicon glyphicon-edit"></span> 
Update card
{% endblock %}

{% block buttons %}
<button  type="button" data-shell="#bigModalContent" 
data-show="{% url 'note_app:list-notes' note.card.id %}"
class="btn btn-default e-get"> {% trans "Back" %} </button>

<button  type="button" 
data-form="#form-note-data" 
data-shell="#bigModalContent" 
data-shell-error="#bigModalContent" 
data-show="{% url 'note_app:update-note' note.id %}"
class="btn btn-default e-post"> 
{% trans "Update" %}
</button>

{% endblock %}