arcamens/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
# from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='site_app:index')),
     url(r'^core_app/', include('core_app.urls', namespace='core_app')), 
     url(r'^group_app/', include('group_app.urls', namespace='group_app')), 
     url(r'^board_app/', include('board_app.urls', namespace='board_app')), 
     url(r'^comment_app/', include('comment_app.urls', namespace='comment_app')), 
     url(r'^site_app/', include('site_app.urls', namespace='site_app')), 
     url(r'^cash_app/', include('cash_app.urls', namespace='cash_app')), 

     url(r'^post_app/', include('post_app.urls', namespace='post_app')), 
     url(r'^group_app/', include('group_app.urls', namespace='group_app')),
     url(r'^paybills/', include('paybills.urls', namespace='paybills')), 
     url(r'^onesignal/', include('onesignal.urls', namespace='onesignal')), 
    url(r'^board_app/', include('board_app.urls', namespace='board_app')),
    url(r'^card_app/', include('card_app.urls', namespace='card_app')),
    url(r'^snippet_app/', include('snippet_app.urls', namespace='snippet_app')),
    url(r'^note_app/', include('note_app.urls', namespace='note_app')),
    url(r'^jscroll/', include('jscroll.urls', namespace='jscroll')),

    url(r'^bitbucket_app/', include('bitbucket_app.urls', namespace='bitbucket_app')),
    url(r'^github_app/', include('github_app.urls', namespace='github_app')),

    url(r'^list_app/', include('list_app.urls', namespace='list_app')),

]


# handler500 = 'core_app.views.default_error'

board_app/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^list-boards/', views.ListBoards.as_view(), name='list-boards'),
    url(r'^create-board/', views.CreateBoard.as_view(), name='create-board'),
    url(r'^pin-board/(?P<board_id>.+)/', views.PinBoard.as_view(), name='pin-board'),

    url(r'^update-board/(?P<board_id>.+)/', views.UpdateBoard.as_view(), name='update-board'),
    url(r'^paste-list/(?P<board_id>.+)/(?P<list_id>.+)/', views.PasteList.as_view(), name='paste-list'),
    url(r'^paste-all-lists/(?P<board_id>.+)/', views.PasteAllLists.as_view(), name='paste-all-lists'),
    url(r'^select-destin-board/(?P<board_id>.+)/', views.SelectDestinBoard.as_view(), name='select-destin-board'),

    url(r'^delete-board/(?P<board_id>.+)/', views.DeleteBoard.as_view(), name='delete-board'),
    url(r'^login/', RedirectView.as_view(pattern_name='site_app:login'), name='login'),
    url(r'^logout/', RedirectView.as_view(pattern_name='site_app:logout'), name='logout'),
    url(r'^manage-user-boards/(?P<user_id>.+)/', views.ManageUserBoards.as_view(), name='manage-user-boards'),
    url(r'^manage-board-members/(?P<board_id>.+)', views.ManageBoardMembers.as_view(), name='manage-board-members'),
    url(r'^manage-board-admins/(?P<board_id>.+)', views.ManageBoardAdmins.as_view(), name='manage-board-admins'),
    url(r'^list-pins/', views.ListPins.as_view(), name='list-pins'),
    url(r'^unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),
    url(r'^bind-board-user/(?P<board_id>.+)/(?P<user_id>.+)/', views.BindBoardUser.as_view(), name='bind-board-user'),
    url(r'^unbind-board-user/(?P<board_id>.+)/(?P<user_id>.+)/', views.UnbindBoardUser.as_view(), name='unbind-board-user'),
    url(r'^bind-user-board/(?P<board_id>.+)/(?P<user_id>.+)/', views.BindUserBoard.as_view(), name='bind-user-board'),
    url(r'^unbind-user-board/(?P<board_id>.+)/(?P<user_id>.+)/', views.UnbindUserBoard.as_view(), name='unbind-user-board'),

    url(r'^bind-board-admin/(?P<board_id>.+)/(?P<user_id>.+)/', views.BindBoardAdmin.as_view(), name='bind-board-admin'),
    url(r'^unbind-board-admin/(?P<board_id>.+)/(?P<user_id>.+)/', views.UnbindBoardAdmin.as_view(), name='unbind-board-admin'),

    url(r'^board-link/(?P<board_id>.+)/', views.BoardLink.as_view(), name='board-link'),

]

core_app/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.Index.as_view(), name='index'),
    url(r'^set-timezone/$', views.SetTimezone.as_view(), name='set-timezone'),
    url(r'^disabled-account/(?P<user_id>.+)/', views.DisabledAccount.as_view(), name='disabled-account'),
    url(r'^switch-organization/(?P<organization_id>.+)/', views.SwitchOrganization.as_view(), name='switch-organization'),
    url(r'^update-user-information/', views.UpdateUserInformation.as_view(), name='update-user-information'),
    url(r'^create-organization/', views.CreateOrganization.as_view(), name='create-organization'),
    url(r'^select-organization/', views.SelectOrganization.as_view(), name='select-organization'),
    url(r'^no-organization/', views.NoOrganization.as_view(), name='no-organization'),
    url(r'^no-default/', views.NoDefault.as_view(), name='no-default'),

    url(r'^seen-event/(?P<event_id>.+)/', views.SeenEvent.as_view(), name='seen-event'),
    url(r'^setup-node-filter/', views.SetupNodeFilter.as_view(), name='setup-node-filter'),
    url(r'^join-organization/(?P<organization_id>.+)/(?P<token>.+)/', views.JoinOrganization.as_view(), name='join-organization'),
    url(r'^signup-from-invite/(?P<organization_id>.+)/(?P<token>.+)/', views.SignupFromInvite.as_view(), name='signup-from-invite'),
    url(r'^update-organization/', views.UpdateOrganization.as_view(), name='update-organization'),
    url(r'^delete-organization/', views.DeleteOrganization.as_view(), name='delete-organization'),
    url(r'^list-users/', views.ListUsers.as_view(), name='list-users'),
    url(r'^manage-user-tags/(?P<user_id>.+)', views.ManageUserTags.as_view(), name='manage-user-tags'),
    url(r'^list-events/', views.ListEvents.as_view(), name='list-events'),
    url(r'^shout/', views.Shout.as_view(), name='shout'),
    url(r'^list-logs/', views.ListLogs.as_view(), name='list-logs'),
    url(r'^all-seen/', views.AllSeen.as_view(), name='all-seen'),

    url(r'^list-tags/', views.ListTags.as_view(), name='list-tags'),
    url(r'^bind-user-tag/(?P<user_id>.+)/(?P<tag_id>.+)/', views.BindUserTag.as_view(), name='bind-user-tag'),
    url(r'^unbind-user-tag/(?P<user_id>.+)/(?P<tag_id>.+)/', views.UnbindUserTag.as_view(), name='unbind-user-tag'),
    url(r'^create-tag/', views.CreateTag.as_view(), name='create-tag'),
    url(r'^delete-tag/(?P<tag_id>.+)/', views.DeleteTag.as_view(), name='delete-tag'),
    url(r'^invite-organization-user/', views.InviteOrganizationUser.as_view(), name='invite-organization-user'),
    url(r'^list-clipboard/', views.ListClipboard.as_view(), name='list-clipboard'),
    url(r'^delete-all-clipboard/', views.DeleteAllClipboard.as_view(), name='delete-all-clipboard'),
    url(r'^confirm-clipboard-deletion/', views.ConfirmClipboardDeletion.as_view(), name='confirm-clipboard-deletion'),
    url(r'^update-password/', views.UpdatePassword.as_view(), name='update-password'),

    url(r'^disabled-account/$', views.DisabledAccount.as_view(), name='disabled-account'),
    url(r'^remove-organization-user/(?P<user_id>.+)', views.RemoveOrganizationUser.as_view(), name='remove-organization-user'),
    url(r'^cancel-invite/(?P<invite_id>.+)', views.CancelInvite.as_view(), name='cancel-invite'),
    url(r'^list-invites/', views.ListInvites.as_view(), name='list-invites'),
    url(r'^manage-organization-admins/', views.ManageOrganizationAdmins.as_view(), name='manage-organization-admins'),
    url(r'^bind-organization-admin/(?P<user_id>.+)/', views.BindOrganizationAdmin.as_view(), name='bind-organization-admin'),
    url(r'^unbind-organization-admin/(?P<user_id>.+)/', views.UnbindOrganizationAdmin.as_view(), name='unbind-organization-admin'),
    url(r'^resend-invite/(?P<invite_id>.+)', views.ResendInvite.as_view(), name='resend-invite'),
    url(r'^list-nodes/', views.ListNodes.as_view(), name='list-nodes'),
    url(r'^resend-email-confirmation/', views.ResendEmailConfirmation.as_view(), name='resend-email-confirmation'),

]

list_app/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list-lists/(?P<board_id>.+)/', views.ListLists.as_view(), name='list-lists'),
    url(r'^update-list/(?P<list_id>.+)/', views.UpdateList.as_view(), name='update-list'),
    url(r'^create-list/(?P<board_id>.+)/', views.CreateList.as_view(), name='create-list'),
    url(r'^delete-list/(?P<list_id>.+)/', views.DeleteList.as_view(), name='delete-list'),
    url(r'^pin-list/(?P<list_id>.+)/', views.PinList.as_view(), name='pin-list'),
    url(r'^select-destin-list/(?P<list_id>.+)/', views.SelectDestinList.as_view(), name='select-destin-list'),
    url(r'^paste-card/(?P<list_id>.+)/(?P<card_id>.+)/', views.PasteCard.as_view(), name='paste-card'),
    url(r'^paste-all-cards/(?P<list_id>.+)/', views.PasteAllCards.as_view(), name='paste-all-cards'),
    url(r'^cut-list/(?P<list_id>.+)/', views.CutList.as_view(), name='cut-list'),
    url(r'^copy-list/(?P<list_id>.+)/', views.CopyList.as_view(), name='copy-list'),
    url(r'^setup-list-filter/(?P<board_id>.+)', views.SetupListFilter.as_view(), name='setup-list-filter'),
    url(r'^undo-clipboard/(?P<list_id>.+)/', views.UndoClipboard.as_view(), name='undo-clipboard'),
    url(r'^list-link/(?P<list_id>.+)/', views.ListLink.as_view(), name='list-link'),
    url(r'^confirm-list-deletion/(?P<list_id>.+)/', views.ConfirmListDeletion.as_view(), name='confirm-list-deletion'),
    url(r'^unpin/(?P<pin_id>.+)/', views.Unpin.as_view(), name='unpin'),

]

board_app/models.py
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from core_app.models import  User, Organization, Event, Node
from django.core.urlresolvers import reverse
from sqlike.parser import SqLike, SqNode
from django.db.models import Q
from django.db import models

class BoardPinMixin(object):
    def get_absolute_url(self):
        return reverse('list_app:list-lists', 
            kwargs={'board_id': self.board.id})

class BoardMixin(models.Model):
    class Meta:
        abstract = True

    @classmethod
    def from_sqlike(cls):
        default = lambda ind: Q(name__icontains=ind) |\
         Q(description__icontains=ind)

        sqlike = SqLike(cls, SqNode(None, default))
        return sqlike

    @classmethod
    def get_user_boards(cls, user):
        boards = user.boards.filter(organization=user.default)
        return boards

    def get_ancestor_url(self):
        return reverse('board_app:list-boards')

    def get_link_url(self):
        return reverse('board_app:board-link', 
                    kwargs={'board_id': self.id})

    def save(self, *args, **kwargs):
        # The node objects should be created just once.
        if not self.pk:
            self.node = Node.objects.create()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def revoke_access(self, admin, user):
        """
        Remove user access and allow admin access. Set ownership
        to admin if the user is the owner of the board.
        """

        self.members.remove(user)
        self.admins.remove(user)

        if self.owner == user: 
            self.set_ownership(admin)

    def set_ownership(self, admin):
        self.members.add(admin)
        self.admins.add(admin)

        self.owner = admin
        self.save()            

class EBindBoardUserMixin(object):
    pass

class EUnbindBoardUserMixin(object):
    pass

class EUpdateBoardMixin(object):
    pass

class ECreateBoardMixin(object):
    pass

class Boardship(models.Model):
    """    
    """
    board = models.ForeignKey('Board', null=True, blank=True)

    member = models.ForeignKey('core_app.User', null=True, 
    related_name='member_boardship', blank=True)

    binder = models.ForeignKey('core_app.User', null=True, 
    related_name='binder_boardship', blank=True)

    created = models.DateTimeField(auto_now_add=True, null=True)
    admin   = models.BooleanField(default=False)

    class Meta:
        unique_together = ('board', 'member', )

class Board(BoardMixin):
    """    
    """
    organization = models.ForeignKey('core_app.Organization', 
    related_name='boards', null=True, blank=True)

    name = models.CharField(null=True, blank=False,
    verbose_name=_("Name"), help_text='Example: Arcamens', max_length=250)

    description = models.CharField(blank=True, default='', 
    verbose_name=_("Description"), help_text='Example: /projectname/', max_length=626)

    owner = models.ForeignKey('core_app.User', null=True, 
    blank=True, related_name='owned_boards')

    created  = models.DateTimeField(auto_now_add=True, 
    null=True)

    open = models.BooleanField(blank=True, default=False,
    help_text='Include all organization members.')

    members = models.ManyToManyField('core_app.User', through=Boardship,
    null=True, related_name='boards', blank=True, symmetrical=False,
    through_fields=('board', 'member'))

    node = models.OneToOneField('core_app.Node', 
    null=False, related_name='board')

    # done = models.BooleanField(blank=True, default=False)

class BoardPin(BoardPinMixin, models.Model):
    user = models.ForeignKey('core_app.User', null=True, blank=True)

    organization = models.ForeignKey('core_app.Organization', 
    blank=True, null=True)

    board = models.ForeignKey('board_app.Board', null=True, blank=True)

    class Meta:
        unique_together = ('user', 'organization', 'board')

class EBindBoardUser(Event, EBindBoardUserMixin):
    board = models.ForeignKey('Board', 
    related_name='e_bind_board_user', blank=True)

    peer = models.ForeignKey('core_app.User', null=True, blank=True)
    html_template = 'board_app/e-bind-board-user.html'

class EUnbindBoardUser(Event, EUnbindBoardUserMixin):
    board = models.ForeignKey('Board', 
    related_name='e_unbind_board_user', blank=True)
    peer = models.ForeignKey('core_app.User', null=True, blank=True)
    html_template = 'board_app/e-unbind-board-user.html'

class EUpdateBoard(Event, EUpdateBoardMixin):
    board = models.ForeignKey('Board', 
    related_name='e_update_board', blank=True)
    html_template = 'board_app/e-update-board.html'

class ECreateBoard(Event, ECreateBoardMixin):
    board = models.ForeignKey('Board', 
    related_name='e_create_board', blank=True)
    html_template = 'board_app/e-create-board.html'

class EDeleteBoard(Event):
    board_name = models.CharField(max_length=250, 
    blank=True, null=True)
    html_template = 'board_app/e-delete-board.html'

class EPasteList(Event, ECreateBoardMixin):
    board = models.ForeignKey('Board', 
    related_name='e_paste_list0', blank=True)

    lists = models.ManyToManyField('list_app.List', 
    null=True, related_name='e_paste_list1', blank=True, 
    symmetrical=False)

    html_template = 'board_app/e-paste-list.html'

board_app/forms.py
from group_app.forms import ConfirmGroupDeletionForm
from sqlike.forms import SqLikeForm
from django import forms
from . import models
import card_app.models

class BoardForm(forms.ModelForm):
    class Meta:
        model  = models.Board
        exclude = ('owner', 'main', 'admins',
        'members', 'organization', 'node')

class UpdateBoardForm(forms.ModelForm):
    class Meta:
        model  = models.Board
        exclude = ('owner', 'main', 'admins',
        'members', 'organization', 'node', 'open')

class BindUsersForm(forms.Form):
    email = forms.EmailField()
    admin = forms.BooleanField(required=False)

class BoardSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False)

class UserSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False)

class ConfirmBoardDeletionForm(ConfirmGroupDeletionForm):
    name = forms.CharField(required=True,
    help_text='Type the board name to confirm!')

board_app/templates/board_app/board.html
{% load i18n %}

<div class="panel panel-default board" >
<div class="panel-body text-center">

<div class="pull-right"> <a class=" e-get text-default"  href="#" 
data-shell="#pins"  data-show="{% url 'board_app:pin-board' board.id %}">
<span class="glyphicon glyphicon-paperclip"></span> </a> </div>


<p> <a class="e-get" data-shell="#main-view"  data-show="{% url 'list_app:list-lists' board.id %}" href="{{board.get_link_url}}">
<em ><span class="glyphicon glyphicon-th"></span> Board </em> {{board.name}} 
<br>
{{board.description}} 

</a> 


</p> 

<small> <a href="#" data-toggle="popover" data-trigger="hover" title="{{board.owner.email}}"  data-content="{{board.owner.description}}">
{{board.owner.name}} </a> on <a href="{{board.get_link_url}}" target="_blank"> {{board.created}} </small> </a>

</div> 


</div>

board_app/templates/board_app/list-pins.html
{% load i18n %}

<div id="pins">
<ul class="nav nav-pills" id="pinned-cards" style="font-size:80%">


<li><a class="e-get disabled" style="color:black; pointer-events: none;" href="#">
<span class="glyphicon glyphicon-paperclip"></span> Pins:</a></li>

{% for ind in boardpins %}
<li> <a class="e-get pin-board" data-shell="#main-view"
data-show="{{ ind.get_absolute_url }}" href="#"> <span class="glyphicon glyphicon-th"></span>  {{ind.board.name|truncatechars:20}}
<span  onclick="$('#pins').load('{% url 'board_app:unpin' ind.id %}');event.stopPropagation();" class="close">
&times; </span> </a>
</li>

{% endfor %}

{% for ind in listpins %}
<li > <a class="e-get pin-list" data-shell="#main-view"
data-show="{{ ind.get_absolute_url }}" href="#"> <span class="glyphicon glyphicon-list-alt"> </span>
{{ind.list.ancestor.name|truncatechars:15}} <span class="glyphicon glyphicon-arrow-right"></span> {{ind.list.name|truncatechars:15}}
<span class="close" onclick="$('#pins').load('{% url 'list_app:unpin' ind.id %}');event.stopPropagation();">&times;</span> </a>
</li>

{% endfor %}

{% for ind in cardpins %}
<li> <a class="e-get pin-card"  data-shell="#bigModalContent" data-show="{{ ind.get_absolute_url }}" href="#">
<span class="glyphicon glyphicon-file"></span> {{ind.card.label|truncatechars:20}}

<span class="close" onclick="$('#pins').load('{% url 'card_app:unpin' ind.id %}');event.stopPropagation();">&times;</span> </a>
</li>
{% endfor %}

{% for ind in grouppins %}
<li>
<a class="e-get pin-group"  data-shell="#main-view"
data-show="{{ ind.get_absolute_url }}" href="#"> <span class="glyphicon glyphicon-eye-open"></span>  {{ind.group.name}}
<span  onclick="$('#pins').load('{% url 'group_app:unpin' ind.id %}');event.stopPropagation();" class="close">
&times;
</span> </a>
</li>
{% endfor %}

{% for ind in postpins %}
<li>
<a class="e-get pin-post"  data-shell="#main-view"
data-show="{{ ind.get_absolute_url }}" href="#"> <span class="glyphicon glyphicon-file"></span>  {{ind.post.label|truncatechars:20}}
<span  onclick="$('#pins').load('{% url 'post_app:unpin' ind.id %}');event.stopPropagation();" class="close">
&times;
</span> </a>
</li>
{% endfor %}

</ul>

</div>

<!--
// <script>
// $( function() {
// $( "#pinned-cards" ).sortable({
    // helper: "clone",
    // axis:'x'});
// });
// </script>
-->

board_app/templates/board_app/manage-board-admins.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% load avatar %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
{{board.name|truncatechars:20}}'s Admins 
<span class="badge">{{count}}/{{total}}</span>
</h5>
</div>

<div class="modal-body">

<div class="pre-scrollable">
{% for ind in included %}
<p class="text-center" >
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}  
<br>

<small> {{ind.email}} </small>   

<br>

<a class="e-post" style="color:red; font-size:70%" data-form="#userSearchForm"
data-show="{% url 'board_app:unbind-board-admin' board.id ind.id %}"  href="#"> 
<span class="glyphicon glyphicon-remove"></span> Remove</a>  

</p>

{% endfor %}

{% for ind in excluded %}
<p class="text-center" >
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}  
<br>

<small> {{ind.email}} </small>  
<br>

<a class="e-post" style="color:green;font-size:70%" data-form="#userSearchForm"
data-show="{% url 'board_app:bind-board-admin' board.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> Add </a> 

</p>
{% endfor %}
</div>

<br>
<form id="userSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">

<button  type="button" data-form="#userSearchForm" data-shell="#smallModalContent" 
data-shell-error="#smallModalContent" data-show="{% url 'board_app:manage-board-admins' board.id  %}"
class="btn btn-default e-post"> {% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

board_app/templates/board_app/manage-board-members.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% load avatar %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
Available {{board.name|truncatechars:20}}'s Members 
<span class="badge">{{count}}/{{total}}</span>
</h5>
</div>

<div class="modal-body">

<div class="pre-scrollable">
{% for ind in included %}
<p class="text-center">
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}  
<br>

<small> {{ind.email}} </small>   <br>

<a class="r-post" data-form="#userSearchForm" style="color:red;font-size:70%"
data-show="{% url 'board_app:unbind-board-user' board.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> Unbind</a>  

</p>

{% endfor %}

{% for ind in excluded %}
<p class="text-center">
<img class="img-responsive center-block"  width="50" height="50"  src="{% avatar ind.avatar %}" />
{{ind.name}}
<br>

<small> {{ind.email}} </small>  
<br>

<a class="r-post" data-form="#userSearchForm" style="color:green;font-size:70%"
data-show="{% url 'board_app:bind-board-user' board.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> Bind </a> 

</p>
{% endfor %}
</div>

<br> 
<form id="userSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">

<button  type="button" data-form="#userSearchForm"  data-show="{% url 'board_app:manage-board-members' board.id  %}"
class="btn btn-default e-post"> {% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

board_app/templates/board_app/manage-user-boards.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
Available {{user.name}}'s Boards <span class="badge">{{count}}/{{total}}</span></h5>
</div>

<div class="modal-body">
<div class="pre-scrollable">
{% for ind in included %}
<p>
<a class="r-post" style="color:red" data-form="#boardSearchForm"
data-show="{% url 'board_app:unbind-user-board' ind.id user.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> </a> 

<b> {{ind.name}} </b>
{{ind.description}}
</p>
{% empty %}
<p> ... </p>

{% endfor %}

{% for ind in excluded %}
<p>
<a class="r-post" data-form="#boardSearchForm"
data-show="{% url 'board_app:bind-user-board' ind.id user.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> </a> 

<b> {{ind.name}} </b>
{{ind.description}}
</p>
{% empty %}
<p> ... </p>

{% endfor %}

</div>

<br> 
<form id="boardSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>

</div>

<div class="modal-footer">
{% block buttons %}

<button  type="button" 
data-shell="#smallModalContent" 
data-show="{% url 'core_app:list-users'  %}"
class="btn btn-default e-get"> {% trans "Back" %} </button>
{% endblock %}

<button  type="button" data-form="#boardSearchForm" data-shell="#smallModalContent" 
data-show="{% url 'board_app:manage-user-boards' user.id  %}"
class="btn btn-default e-post"> {% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

board_app/templates/board_app/update-board.html
{% load bootstrap3 %}

{% load i18n %}

<div class="modal-header">
<button type="button"  class="close" data-dismiss="modal">&times;</button>
<h5>  <span class="glyphicon glyphicon glyphicon-cog"></span> Settings </h5>

</div>

<div class="modal-body">
<form id="form-board-data" enctype="multipart/form-data">
{% csrf_token %}

{% bootstrap_field form.name  size='md' %}
{% bootstrap_field form.description  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}

</form>
{% if board.open %}  
<p class="text-info"> This board is open.  </p>
{% endif %}
</div>

<div class="modal-footer">
<button  type="button" 
data-show="{% url 'board_app:delete-board' board.id %}"
class="btn btn-danger e-get"> 
{% trans "Delete" %}
</button>

<button  type="button" data-form="#form-board-data" data-shell="#main-view" 
data-show="{% url 'board_app:update-board' board.id %}"
class="btn btn-default e-post"> 
{% trans "Update" %}
</button>

</div>